### ISSUE TITLE
Difference between get_ncov() and get_ncov2()

### ISSUE THREAD

**Issue by aveshenpillay** [pzhaonet/ncovr#15]
`get_ncov()` returns data from 21 Jan 2020 to 05 March 2020 with the following:

```{r}
### Get the latest data

# load required packages
library(ncovr)

# get the latest data
ncov <- get_ncov() 

# extract the area data frame
ncov <- ncov$area

# a function for converting Julian time to ymd_
conv_time <- function(x){
  as.POSIXct('1970-01-01', tz = 'GMT') + x / 1000
}

# convert updateTime from Julian date to ymd-hms
ncov$updateTime <- conv_time(ncov$updateTime)
```

`get_ncov2()` returns cumulative data to to the latest date with the following call:

```{r}
ncov2 <- get_ncov2()
```

How do you get a complete data set from inception to current based on each updated time stamp?

**Comment by yiluheihei** [comment]
`get_ncov()` return a list,  contains `area`,  `overall`, `news` and `rumors` data from this [api](https://lab.isaaclin.cn/nCoV/en). 

`get_ncov2()`return a `ncov` class inheris from `data.frame`: a tidy data frame contains the fatten `area` data.  It returns the latest data by default, and you can get the time series data by set `latest = FALSE` , `get_ncov2(latest = FALSE)`.

**Comment by aveshenpillay** [comment]
Ok thanks. I tried to run that and now have the following error:

```{r}
ncov2 <- get_ncov2()
Error in open.connection(con, "rb") : 
  Timeout was reached: [lab.isaaclin.cn] Connection timed out after 10000 milliseconds
```

**Comment by yiluheihei** [comment]
The error indicated that you can not connect the api server, and the server is hosted on Alibaba Cloud East China Zone 2 (Shanghai). 

The data is from https://lab.isaaclin.cn/nCoV/api/, and you can test whether you can access the api server in your web browser.

Moreover, considering some users may not connect the api, I have made a [commit](https://github.com/pzhaonet/ncovr/pull/14/commits/01b47f9a59107a3b13a48eb204f612371b2e3fc9),the new version of `get_ncov2` provides an alternate method to download
the ncov data from the [data repo](https://github.com/yiluheihei/nCoV-2019-Data). 

You can use it after the PR is reviewed and merged. 

```
get_ncov2(method = "ncov")
```

Or, use the function `get_ncov2()` in [this package](https://github.com/yiluheihei/ncovmap)

**Comment by aveshenpillay** [comment]
It's working perfectly now, thank you!
